spring:
  datasource:
    url: jdbc:mysql://localhost:3306/first_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        allow_update_outside_transaction: true
  mvc:
    hidden-method:
      filter:
        enabled: true

